# Generated by Django 3.2.13 on 2022-06-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
